name: starter_kit
description: "A comprehensive, scalable, and production-ready Flutter boilerplate generator with clean architecture."
version: 0.0.1
homepage: https://github.com/yourgithub/starter_kit
repository: https://github.com/yourgithub/starter_kit

environment:
  sdk: ^3.7.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Networking
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # State Management (Both options available)
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2
  
  # Model Generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  
  # Utilities
  logger: ^2.0.2+1
  intl: ^0.19.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  uuid: ^4.3.3
  
  # CLI Tools - for the executable
  args: ^2.4.2
  mason_logger: ^0.2.11
  path: ^1.8.3
  recase: ^4.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  riverpod_test: ^0.1.4
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  injectable_generator: ^2.4.1

# Executable for CLI tools
executables:
  starter_kit: main

flutter:
  # Assets that will be included in the package
  assets:
    - assets/templates/
    - assets/icons/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
